'\" -*- coding: utf-8 -*-
.if \n(.g .ds T< \\FC
.if \n(.g .ds T> \\F[\n[.fam]]
.de URL
\\$2 \(la\\$1\(ra\\$3
..
.if \n(.g .mso www.tmac
.TH Open-Sankore 1 "Jun 2012" "Version 3.1" "Open-Sankoré"
.SH NAME
Open-Sankore \- The Free Interactive Whiteboard Software
.SH SYNOPSIS
'nh
.fi
.ad l
\fBOpen-Sankore\fR

.SH DESCRIPTION
The Open-Sankoré software in 5 points
.PP
The Open-Sankoré program is an interactive, free, and Open-Source digital teaching program with high value added.
.TP
\*(T<\fB1. An ergonomic program\fR\*(T>
.PP
Since its inception, Open-Sankoré was designed for and with users/teachers. Thanks to a team composed of specialists and developers, this application to each on a DIT came into being. With an ergonomic interface, it combines the simplicity of traditional teaching tools with the advantages provided by teaching ICTs. Automatic document backup prevents the loss of data. The subtle integration of external components such as those derived from the web or screen captures prevents having to systematically juggle applications and tiring the audience.
.TP
\*(T<\fB2. A universal program\fR\*(T>
.PP
The Open-Sankoré program is a multiplatform, open-source program that is compatible with every type of DIT. It is also translated into many languages and remains adapted to all users: from beginners to experts.
.TP
\*(T<\fB3. A program dedicated to education\fR\*(T>
.PP
In addition to being able to comment, draw, and highlight, the Open-Sankoré program gives you the option of enriching your course content by importing flash animations, images, audio, videos, or by including existing .pdf or .ppt documents.
You can captivate your audience by embedding dynamic content into your course: apps from widgets, Wikipedia, or Google Maps).
The Open-Sankoré program also offers tools for the different phases of a lesson: you can display only the essential part, with appropriate tools such as dynamic screen management or infinite zoom, etc.
Lastly, you can share your resources by publishing them in .PDF document form or as podcasts, or on the web by exporting them to the http://planete.sankore.org portal.
.TP
\*(T<\fB4. Much more than just software...\fR\*(T>
.PP
The Open-Sankoré is part of a broader ecosystem dedicated to digital teaching. The Sankoré community lets you quickly access content and rich, varied digital teaching resources. Join it by going to the http://planete.sankore.org portal.
Here you will find full, scalable tutorials that will enable you to quickly learn the Open-Sankoré program and optimize your lessons.
Development of the SSS program is also in line with an approach of solidarity and education, aimed at reducing the various digital divides.
.TP
\*(T<\fB5. A program that is open-source, scalable, and free\fR\*(T>
.PP
The Open-Sankoré program is free. It has an open code and file format.
.PP
It can continuously be studied, perfected, and adapted to new needs.
.PP
The possibility of creating “apps” gives it even more flexibility.

.SH AUTHOR
This manual has been composed by Mike Gabriel <mike.gabriel@das-netzwerkteam.de> for the Debian distribution (and may be used by others).
.PP
The content of this manual page has been obtained from the Open-Sankoré homepage.

